---
- hosts: devmachine
  tasks:
    - name: checking os family and arch
      debug: msg={{ ansible_os_family }}-{{ ansible_distribution_major_version }}
      failed_when: ansible_os_family != 'Debian' or ansible_architecture != 'x86_64'

    - name: install fundamental tools from package manager
      become: true
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - emacs
          - vim
          - pandoc
          - zsh
          - tmux
          - fzf
          - git
          - git-lfs
          - fzf
          - htop
          - jq
          - pv
          - ripgrep
          - unar
          - lv
          - nkf
          - imagemagick
          - ffmpeg
          - sshpass
          # debian
          - xsel

    - name: Install ghq
      ansible.builtin.include_role:
        name: "common"
      vars:
        cmd: ghq
        new_ver: 1.6.3
        get_ver_cmd: ghq --version | awk '{print $3}'
        url: "https://github.com/motemen/ghq/releases/download/v{{ new_ver }}/ghq_linux_amd64.zip"
        checksum: sha1:a15ee03c1a98fa1e50e3e9a6c1ac2688851f0072
        unpackcmd: /tmp/ghq_linux_amd64/ghq

    - name: Install peco
      ansible.builtin.include_role:
        name: "common"
      vars:
        cmd: peco
        new_ver: 0.5.11
        get_ver_cmd: peco --version
        url: "https://github.com/peco/peco/releases/download/v{{ new_ver }}/peco_linux_amd64.tar.gz"
        checksum: sha1:cce14311ce07a25a37313a8a3154b515c5097f35
        unpackcmd: /tmp/peco_linux_amd64/peco

