---
- hosts: devmachine
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"

  tasks:
    - name: checking os family and arch
      debug: msg={{ ansible_os_family }}-{{ ansible_distribution_major_version }}
      failed_when: ansible_os_family != 'Debian' or ansible_architecture != 'x86_64'

    - name: install fundamental tools from package manager
      become: true
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - emacs
          - vim
          - ibus-mozc
          - zsh
          - libnotify-bin
          - tmux
          - git
          - git-lfs
          - terminator
          - xsel
          - lv
          - pv
          - unar
          - pandoc
          - jq

    - name: install c++ tools
      become: true
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - build-essential
          - cmake
          - clang-format
          - llvm
          - global
          - libboost-all-dev

- name: Install ghq
  import_playbook: common/gobinary_install.yml
  vars:
    cmd: ghq
    new_ver: 0.12.6
    get_ver_cmd: ghq --version | awk '{print $3}'
    url: "https://github.com/motemen/ghq/releases/download/v{{ new_ver }}/ghq_linux_amd64.zip"
    checksum: sha1:aec65496a7c84f7384377e68ef975775d8bdcc52
    unpackcmd: /tmp/ghq_linux_amd64/ghq

- name: Install peco
  import_playbook: common/gobinary_install.yml
  vars:
    cmd: peco
    new_ver: 0.5.3
    get_ver_cmd: peco --version | awk '{print $3}' | sed -e 's/v//g'
    url: "https://github.com/peco/peco/releases/download/v{{ new_ver }}/peco_linux_amd64.tar.gz"
    checksum: sha1:f628f397616f71b20ad60d35909a19e5e2a30701
    unpackcmd: /tmp/peco_linux_amd64/peco
