---
- hosts: devmachine

  tasks:
    - name: homebrew taps
      homebrew_tap:
        name: "{{ repositories }}"
        state: present
      vars:
        repositories:
          - homebrew/cask-fonts
          - yuu/cask-fonts
          - 1password/tap

    - name: install fundamental tools from brew
      homebrew:
        name: "{{ packages }}"
        state: present
        update_homebrew: false
      vars:
        packages:
          - zsh
          - tmux
          - reattach-to-user-namespace
          - terminal-notifier
          - gnu-tar
          - grep
          - git
          - git-lfs
          - ghq
          - peco
          - htop
          - jq
          - pv
          - ripgrep
          - unar
          - lv
          - docker-completion
          - zsh-completion
          - aws-vault
          - imagemagick
          - mas
          - nkf
          - ffmpeg
          - direnv

    - name: install fundamental tools from cask
      homebrew_cask:
        name: "{{ packages }}"
        state: present
        update_homebrew: false
      vars:
        packages:
          - bettertouchtool
          - karabiner-elements
          - dash
          - google-chrome
          - brave-browser
          - google-japanese-ime
          - discord
          - gpg-suite
          - docker
          - keycast
          - licecap
          - blu-ray-player
          - vlc
          - gimp
          - brave-browser
          - raycast
          - jasper
          - vnc-viewer
          - ngrok
          - kap
          - obs
          - google-drive
          - alacritty
          - 1password-cli
          - obsidian
          - cloudflare-warp

    - name: install fonts
      homebrew_cask:
        name: "{{ fonts }}"
        state: present
        update_homebrew: true
      vars:
        fonts:
          - font-source-code-pro
          - font-source-han-code-jp

    # general
    - name: Show scroll bars
      # Automatically based on mouse or trackpad: Automatic
      # When scrolling: WhenScrolling
      # Always: Always
      osx_defaults:
        key: AppleShowScrollBars
        type: string
        value: Automatic

    - name: Click in the scroll bar to
      # Jump to the next page: 0
      # Jump to the spot that's clicked: 1
      osx_defaults:
        key: AppleScrollerPagingBehavior
        type: int
        value: 1

    # keyboard
     # keyboard
    - name: Key Repeat
      osx_defaults:
        key: KeyRepeat
        type: int
        value: 2

    - name: Delay Until Repeat
      osx_defaults:
        key: InitialKeyRepeat
        type: int
        value: 15

    - name: Use F1, .., keys as standard function keys
      osx_defaults:
        key: com.apple.keyboard.fnState
        type: int
        value: 0
     # shortcuts
     # input sources

    # trackpad
    - name: Tracking speed
      osx_defaults:
        key: com.apple.trackpad.scaling
        type: float
        value: 3

    - name: Scroll direction Natural
      osx_defaults:
        key: com.apple.swipescrolldirection
        type: int
        value: 0

    - name: Removing window shadows with screen capture
      osx_defaults:
        domain: com.apple.screencapture
        key: disable-shadow
        type: bool
        value: true

    - name: Rearrange automatically keep the space arragement
      osx_defaults:
        domain: com.apple.dock
        key: mru-spaces
        type: bool
        value: false
      tags:
        - defaults

- name: Install lltsv
  import_playbook: common/gobinary_install.yml
  vars:
    cmd: lltsv
    new_ver: v0.7.0
    get_ver_cmd: lltsv --version
    url: "https://github.com/sonots/lltsv/releases/download/{{ new_ver }}/lltsv_darwin_amd64"
    checksum: sha1:f628f397616f71b20ad60d35909a19e5e2a30701
    unpackcmd: /tmp/
  tags:
    - debug
