---
- hosts: devmachine

  tasks:
    - name: homebrew taps
      homebrew_tap:
        name: "{{ repositories }}"
        state: present
      vars:
        repositories:
          - homebrew/cask-fonts

    - name: install fundamental tools from brew
      homebrew:
        name: "{{ packages | map(attribute='name') | list }}"
        install_options: "{{ packages | map(attribute='opt') | list }}"
        state: present
        update_homebrew: no
      vars:
        packages:
          - { name: zsh, opt: '' }
          - { name: tmux, opt: '' }
          - { name: reattach-to-user-namespace, opt: '' }
          - { name: terminal-notifier, opt: '' }
          - { name: gnu-tar, opt: '' }
          - { name: grep, opt: 'with-default-names' }
          - { name: emacs, opt: '' }
          - { name: git, opt: '' }
          - { name: git-lfs, opt: '' }
          - { name: ghq, opt: '' }
          - { name: peco, opt: '' }
          - { name: htop, opt: '' }
          - { name: jq, opt: '' }
          - { name: pv, opt: '' }
          - { name: ripgrep, opt: '' }
          - { name: unar, opt: '' }
          - { name: lv, opt: '' }
          # c/c++
          - { name: llvm, opt: '' }
          - { name: clang-format, opt: '' }
          - { name: cmake, opt: '' }
          - { name: ccls, opt: '' }
          # go
          - { name: go, opt: '' }
          - { name: dep, opt: '' }
          # swift
          - { name: carthage, opt: '' }
          - { name: swiftlint, opt: '' }
          # nodejs
          - { name: node, opt: '' }
          # misc
          - { name: graphviz, opt: '' }
          - { name: hugo, opt: '' }
          - { name: ipython, opt: '' }
          - { name: markdown, opt: '' }
          - { name: nmap, opt: '' }
          - { name: socat, opt: '' }

    - name: install fundamental tools from cask
      homebrew_cask:
        name: "{{ packages }}"
        state: present
        update_homebrew: no
      vars:
        packages:
          - bettertouchtool
          - karabiner-elements
          - dash
          - day-o
          - google-chrome
          - google-japanese-ime
          - dropbox
          - discord
          - emacs
          - iterm2
          - gpg-suite
          - docker
          - keycast
          - licecap
          - blu-ray-player
          - vlc
          - gimp
          - sketch

    - name: install fonts
      homebrew_cask:
        name: "{{ fonts }}"
        state: present
      vars:
        fonts:
          - font-source-code-pro
          - font-source-han-code-jp
          - font-symbola

    # keyboard
     # keyboard
    - name: Key Repeat
      osx_defaults:
        key: KeyRepeat
        type: int
        value: 2

    - name: Delay Until Repeat
      osx_defaults:
        key: InitialKeyRepeat
        type: int
        value: 15

    - name: Use F1, .., keys as standard function keys
      osx_defaults:
        key: com.apple.keyboard.fnState
        type: int
        value: 0
     # shortcuts
     # input sources

    # trackpad
    - name: Tracking speed
      osx_defaults:
        key: com.apple.trackpad.scaling
        type: float
        value: 3

    - name: Scroll direction Natural
      osx_defaults:
        key: com.apple.swipescrolldirection
        type: int
        value: 0
