---
- hosts: devmachine
  gather_facts: no
  vars:
    cmd: ""
    new_ver: 0.0.0
    get_ver_cmd: "{{ cmd }} --version"
    url: ""
    checksum: ""
    unpackcmd: ""

  tasks:
    - name: "get current version for {{ cmd }}"
      command: "{{ get_ver_cmd }}"
      register: current_ver
      changed_when: False
      failed_when: False

    - name: "download file for {{ cmd }}"
      get_url:
        url: "{{ url }}"
        dest: /tmp
        checksum: "{{ checksum }}"
        force: True
      when:
        - current_ver.rc != 0

    - name: unarchive
      unarchive:
        src: "/tmp/{{ url.split('/')[-1] }}"
        dest: /tmp
      when:
        - current_ver.rc != 0

    - name: install
      become: True
      copy:
        src: "{{ unpackcmd }}"
        dest: /usr/local/bin
        mode: 0755
        owner: root
      when:
        - current_ver.rc != 0
