name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: lint
      uses: ansible/ansible-lint-action@v4.1.0
      with:
        targets: debian.yml
