name: Lint

on: [push]

jobs:
  lint_on_debian:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        # Version range or exact version of a Python version to use, using semvers version range syntax.
        python-version: '3.x'
        # The target architecture (x86, x64) of the Python interpreter.
        architecture: x64

    - uses: actions/cache@v1
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint playbook
      run: |
        ansible-playbook debian.yml --syntax-check
        ansible-lint debian.yml

  lint_on_macos:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1

      - name: Setup Python environment
        uses: actions/setup-python@v1.1.1
        with:
          python-version: '3.x'
          architecture: x64

      - uses: actions/cache@v1
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint playbook
        run: |
          ansible-playbook macos.yml --syntax-check
          ansible-lint macos.yml
