name: main

on: [push]

jobs:
  test:
    name: Test on debian testing on docker
    runs-on: ubuntu-18.04
    container:
      image: debian:testing

    steps:
    - uses: actions/checkout@v1

    - name: lint
      uses: ansible/ansible-lint-action@v4.1.0
      with:
        target: debian.yml
